Makefile
profiles/apparmor.d/local/opt.openqa-trigger-from-obs.script.rsync.sh
profiles/apparmor.d/opt.openqa-trigger-from-obs.script.rsync.sh
script/rsync.sh
t/docker/lib/test-in-container-systemd.sh
t/docker/openSUSE:Leap:15.2:Staging:A.sh

Root cause of the problem is that `ln -f` wants to create temporary file in destination folder when target already exists and that wasn't allowed by apparmor and didn't have proper test.
rsync.sh has strict rules for writing destinations to protect scripts created during deployment.
Thus this fix avoids using -f flag in `ln` and makes sure that .run_last link is deleted before linking to most recent run (plus provides corresponding checks in the test)

Fix second run with apparmor

---

script/rsync.sh
t/docker/Virtualization:WSL.sh
t/docker/rsync.sh.Virtualization:WSL.sh

Save current status files (e.g. minion's job_id) into log folder .run to show later in ObsRsync UI https://github.com/os-autoinst/openQA/pull/2534

Copy status files to .run* folder

---

script/scriptgen.py
t/obs/openSUSE:Factory:ARM:ToTest/jeos-aarch64/files_asset.lst
t/obs/openSUSE:Factory:ARM:ToTest/jeos-aarch64/print_openqa.before
t/obs/openSUSE:Factory:ARM:ToTest/jeos-aarch64/print_rsync_iso.before
xml/obs/openSUSE:Factory:ARM.xml

This should fix the missing asset when testing vagrant on RPi4 - https://progress.opensuse.org/issues/73564

Factory:ARM: Add libvirt.box asset to RPi3 image - poo#73564

---

script/cfg.py

[Openqa schedule command](https://openqa.suse.de/admin/obs_rsync/SUSE:SLE-15-SP3:GA:TEST%7Cjeos/runs/.run_last/download/print_openqa.sh) has omitted VMware jobs
After update:
```
declare -A flavor_filter
flavor_filter[JeOS-for-RaspberryPi]='.*JeOS.*RaspberryPi.*\.raw\.xz$'
flavor_filter[JeOS-for-MS-HyperV]='.*JeOS.*MS-HyperV.*\.vhdx\.xz$'
flavor_filter[JeOS-for-kvm-and-xen]='.*JeOS.*kvm-and-xen.*\.qcow2'
flavor_filter[JeOS-for-VMware]='.*JeOS.*VMware.*\.vmdk\.xz$'
declare -A flavor_distri
flavor_distri[JeOS-for-RaspberryPi]='sle'
flavor_distri[JeOS-for-MS-HyperV]='sle'
flavor_distri[JeOS-for-kvm-and-xen]='sle'
flavor_distri[JeOS-for-VMware]='sle'
```

Schedule vmware jobs

---

script/cfg.py
script/scriptgen.py

Previously function was used only for changing dest iso in staging,
but it may be useful in other cases as well.

Rename rsync_iso_staging to rsync_iso_fix_dest

---

script/cfg.py
script/scriptgen.py
t/abs/TestExtractAsRepo1/files_iso.lst
t/abs/TestExtractAsRepo1/print_openqa.before
t/abs/TestExtractAsRepo1/print_rsync_iso.before
t/test_repo_consistent.sh
xml/abs/TestExtractAsRepo.xml

* make sure that isos, extracted in print_rsync_iso are referenced as REPO in isos post;
* make sure that all synced repos are referenced in isos post.

Improve consistensy test of print_openqa output

---

script/scriptgen.py
t/obs/openSUSE:Factory:ARM:ToTest/base/print_rsync_iso.before
t/obs/openSUSE:Factory:ARM:ToTest/jeos-aarch64/print_rsync_iso.before
t/obs/openSUSE:Factory:ToTest/base/print_rsync_iso.before
t/obs/openSUSE:Leap:15.2:ARM:Images:ToTest/print_rsync_iso.before
t/obs/openSUSE:Leap:15.2:Images:ToTest/print_rsync_iso.before
t/obs/openSUSE:Leap:15.3:Images:ToTest/print_rsync_iso.before

On mutiplatform run rsync might try to search aarch64 files in x86_64 folder and report error "No such file".
```
+ rsync --timeout=3600 -tlp4 --specials 'obspublish::openqa/openSUSE:Leap:15.3:Images:ToTest/images/*/*vagrant*libvirt*/Leap-15.3.aarch64-15.3-libvirt_aarch64-Build3.38.vagrant.libvirt.box' /var/lib/openqa/factory/other/
rsync: link_stat "/openSUSE:Leap:15.3:Images:ToTest/images/x86_64/kiwi-images-vagrant:libvirt/Leap-15.3.aarch64-15.3-libvirt_aarch64-Build3.38.vagrant.libvirt.box" (in openqa) failed: No such file or directory (2)
```
Additional asterisk before file name solves the problem.

Fix rsync complaining file not found for multiplatform assets

---

script/cfg.py
script/scriptgen.py

Currently xml with assets doesn't work for multiple architectures because it reads only first asset from remote into files_iso.lst
This PR allow reading all assets and also must include tweak for armv7hl which must receive armv7l files:
https://github.com/os-autoinst/openqa-trigger-from-obs/blob/e139442e156869d434e459d9d9f88fdfb0dd7aca/t/obs/openSUSE:Factory:ARM:ToTest/jeos-armv7hl/files_iso.lst#L2

Support multiarch assets in read_file.sh

---

script/cfg.py

This way, if we want to sync some other file extensions (e.g. txt)
it will end up by default in other. For hdd we can use the same map
we have in create_asset function

Use "other" directory as default for assets and map only iso and hdd

---

.circleci/config.yml

Without it openssh-server was failing to install:
Error: Subprocess failed. Error: RPM failed: find: '/etc/init.d/rc[35].d': No such file or directory
ERROR: neither useradd nor busybox found!

ci: Don't install git

---

script/cfg.py

The way it is parsing the build number now generates 2 numbers if
the string contains `SnapshotX` and `BuildY`.
It even returns 2 numbers and messes up the openqa call.
e.g.
`SUSE-Linux-Enterprise-Server-15-SP3--Snapshot12--x64-Build2.209.appx`
returns
```
12
2.209
```
and it keeps `BUILD=12` and `2.209` at the end of the call without variable
assignation, which makes the call to fail.
With this fix, we make sure we keep only 1 of the numbers, specially
the one at the end.

Fix the way to get BUILD number for WSL images

---

script/cfg.py
script/scriptgen.py
t/obs/openSUSE:Leap:15.2:Images:ToTest/print_openqa.before
t/obs/openSUSE:Leap:15.3:Images:ToTest/print_openqa.before
xml/obs/openSUSE:Leap:15.2:Images.xml
xml/obs/openSUSE:Leap:15.3:Images.xml

This allows creating an additional isos post with specific flavor
to validate container images without reusing JeOS or any other.

Add Containers flavor for Leap images

---

profiles/apparmor.d/opt.openqa-trigger-from-obs.script.rsync.sh

Following error was observed, this commit attemts to fix it:
`openSUSE:Factory:ToTest/base//read_files.sh: line 5: /opt/openqa-trigger-from-obs/openSUSE:Factory:ToTest/base/Media1_openSUSE-Addon-NonOss-ftp-ftp.lst: Permission denied`
`apparmor="DENIED" name="/opt/openqa-trigger-from-obs/openSUSE:factory:ToTest/base/Media1_openSUSE-Addon-NonOss-ftp-ftp.lst" comm="bash"`

Fix permission denied for read_files

---

.circleci/config.yml
script/scriptgen.py
t/obs/KDE:Medias/argon/files_iso.lst
t/obs/KDE:Medias/argon/print_openqa.before
t/obs/KDE:Medias/argon/print_rsync_iso.before
t/obs/KDE:Medias/krypton/files_iso.lst
t/obs/KDE:Medias/krypton/print_openqa.before
t/obs/KDE:Medias/krypton/print_rsync_iso.before
xml/obs/KDE:Medias.xml

Currently those are handled by jenkins.qa.suse.de.
One downside of adding them here is that the `VERSION` value is no longer derived from the ISO name after syncing, but for Krypton that is currently overridden by the medium type anyway.

Add KDE:Medias for syncing Argon and Krypton

---

t/run_docker.sh

The return code is stored in `$s` now and `$?` will be 0
(Followup to #189)

Fix checking for return code

---

script/rsync.sh

Improving #188, now for Factory projects, the rsync.sh will also include 'base' branch while checking Snapshot consistency.

Consider base batch when checking consistency of a batch in Factory

---

script/cfg.py

As we had no uncompressed vmdk images before, these images would land in other directory instead of hdd.

Store uncompressed vmdk in HDD folder

---

script/cfg.py

https://openqa.suse.de/tests/14130499#settings

Missing HDD_1 variable for uncompressed vmdk image

---

script/cfg.py

This is needed by SL Micro 6.0 maintenace jobs even though that ISO will not be booted, it will be needed by botmaster to get feedback from openQA jobs.

Use spdx.json extension as an ISO

---

script/scriptgen.py

This will help override default meta variables like _OBSOLETE=1
I've tried this feature with an xml with `metavars="_OBSOLETE=0"` and I get it right in the isos post.
Example of usage (internal only): https://gitlab.suse.de/openqa/openqa-trigger-from-ibs-plugin/-/merge_requests/194

Allow entering custom meta variables

---

t/obs/systemsmanagement:Agama:Devel/s390x/files_iso.lst
t/obs/systemsmanagement:Agama:Devel/s390x/print_rsync_iso.before
xml/obs/systemsmanagement:Agama:Devel.xml

Related ticket: https://progress.opensuse.org/issues/166253

Remove iso_path="iso" for agama s390x

---

t/obs/systemsmanagement:Agama:Devel/base/print_openqa.before
xml/obs/systemsmanagement:Agama:Devel.xml

We have detected a problem in mentioned XML file that lead to some jobs not launched.
This PR solves that.

Fix x86_64 arch typo in systemsmanagement:Agama:Devel.xml file

---

systemd/openqa-trigger-from-obs-update.service
systemd/openqa-trigger-from-obs-update.timer

See: https://progress.opensuse.org/issues/166433

Add systemd timer and service for updates

---

t/obs/openSUSE:Slowroll:Build:iso/files_iso.lst
t/obs/openSUSE:Slowroll:Build:iso/print_openqa.before
t/obs/openSUSE:Slowroll:Build:iso/print_rsync_iso.before
xml/obs/openSUSE:Slowroll.xml

Adds openSUSE Slowroll (DVD) to the scheduling.
* Related ticket: https://progress.opensuse.org/issues/177859
* Related PR: https://github.com/os-autoinst/opensuse-jobgroups/pull/610

Add Slowroll DVD

---

script/scriptgen.py

https://docs.python.org/dev/whatsnew/3.12.html#other-language-changes
/opt/openqa-trigger-from-ibs/script/scriptgen.py:489: SyntaxWarning: invalid escape sequence '\.'
"""build=$(grep -o -E '(Build|Snapshot)[^-]*' __envsub/files_iso.lst | grep -o -E '[0-9]\.?[0-9]+(\.[0-9]+)*' | head -n 1)""",

Avoid warning about escape sequence in python 3.12

---

script/cfg.py
script/scriptgen.py
t/obs/openSUSE:Leap:16.0:ToTest/print_openqa.before

`MIRROR_PREFIX` is one of the variables needed for https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/22054

Add handling for MIRROR_* variables

---

script/cfg.py
t/obs/openSUSE:Leap:16.0:ToTest/print_openqa.before

This supports automated installations with agama
Goes together with: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/22606

Set INST_INSTALL_URL to same value as MIRROR_HTTPS

---

profiles/apparmor.d/opt.openqa-trigger-from-obs.script.rsync.sh

The file openqa-cli.yaml needs to be readable.
See: https://github.com/os-autoinst/openQA/pull/6316

Add openqa/public needed by openqa-cli to apparmor

---

profiles/apparmor.d/opt.openqa-trigger-from-obs.script.rsync.sh

To address denials like this:
type=AVC msg=audit(1753252655.471:303648): apparmor="DENIED" operation="open" class="file" profile="/opt/openqa-trigger-from-obs/script/rsync.sh//rsync" name="/etc/ssl/openssl.cnf" pid=19240 comm="rsync" requested_mask="r" denied_mask="r" fsuid=493 ouid=0

Add abstractions/openssl to rsync apparmor profile
